apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: operatordeploys.example.com
spec:
  group: example.com
  names:
    kind: Operatordeploy
    listKind: OperatordeployList
    plural: operatordeploys
    singular: operatordeploy
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true
  versions:
  - name: v1alpha1
    served: true
    storage: true
