kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: operator-deploy
subjects:
- kind: ServiceAccount
  name: operator-deploy
roleRef:
  kind: Role
  name: operator-deploy
  apiGroup: rbac.authorization.k8s.io
